AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara:
    - lint/rubocop/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - lib/typescript_remote_command_generator.rb
