RSpec.describe Foobara::RemoteGenerator::GenerateTypescript do
  let(:command) { described_class.new(inputs) }
  let(:outcome) { command.run }
  let(:result) { outcome.result }
  let(:errors) { outcome.errors }
  let(:inputs) { { raw_manifest: } }
  let(:raw_manifest_json) { File.read("spec/fixtures/foobara-manifest.json") }
  let(:raw_manifest) { JSON.parse(raw_manifest_json) }

  it "contains base files" do
    expect(outcome).to be_success

    expect(result.keys).to any match(/base/)
    expect(command.manifest.organizations.map(&:scoped_short_name)).to include("SomeOrg")
    expect(command.manifest.domains.map(&:scoped_short_name)).to include("Auth")
    expect(command.manifest.commands.map(&:command_name)).to include("CreateUser")
    expect(command.manifest.types.map(&:name)).to include("User")
    expect(command.manifest.entities.map(&:entity_name)).to include("User")

    expect(result["SomeOrg/index.ts"]).to include('export const organizationName = "SomeOrg"')
    expect(result["SomeOrg/Auth/index.ts"]).to include('export const domainName = "Auth"')
  end

  # This auth-manifest.json was generated by running blog-rails foobara-demo app and hitting localhost:3000/manifest
  context "when generating typescript for a domain using Foobara::Auth" do
    let(:raw_manifest) { JSON.parse(File.read("spec/fixtures/auth-manifest.json")) }

    it "generates Auth support files and gives commands the proper base classes" do
      expect(outcome).to be_success

      expect(result.keys).to include("Foobara/Auth/LoginCommand.ts")
      expect(result.keys).to include("Foobara/Auth/LogoutCommand.ts")
      expect(result.keys).to include("Foobara/Auth/RequiresAuthCommand.ts")
      expect(result.keys).to include("Foobara/Auth/utils/accessTokens.ts")
    end

    context "when no_foobara_auth is set" do
      let(:inputs) { { raw_manifest:, no_foobara_auth: true } }

      it "generates no RequiresAuthCommand even though the manifest has the domain" do
        expect(outcome).to be_success

        expect(result.keys).to_not include("Foobara/Auth/RequiresAuthCommand.ts")
      end

      it "still generates the commands themselves" do
        expect(outcome).to be_success

        expect(result.keys).to include("Foobara/Auth/LoginCommand.ts")
      end
    end
  end

  describe ".requires_auth_command_generatable?" do
    subject(:generatable) do
      Foobara::RemoteGenerator::Generators::TypescriptFromManifestBaseGenerator
        .requires_auth_command_generatable?(Foobara::Manifest::RootManifest.new(command: commands))
    end

    context "when the manifest has every command those imports come from" do
      let(:commands) do
        { "Foobara::Auth::RefreshLogin" => {}, "Foobara::Auth::Login" => {}, "Billing::Charge" => {} }
      end

      it { is_expected.to be true }
    end

    context "when the refresh endpoint is not exposed" do
      let(:commands) do
        { "Foobara::Auth::Login" => {}, "Foobara::Auth::Logout" => {}, "Billing::Charge" => {} }
      end

      it "is false, because ./RefreshLogin would not be generated" do
        expect(generatable).to be false
      end
    end

    context "when there is no auth domain at all" do
      let(:commands) { { "Billing::Charge" => {} } }

      it { is_expected.to be false }
    end
  end
end
